// uiCopy.ts — nguồn UI chrome copy duy nhất toàn site (DECISIONS 2026-07-10, LOOP-FIX V1)
// Pattern theo HOME_COPY (homepage.ts): Record theo Lang, đủ 5 ngôn ngữ.
// Ranh giới: HOME_COPY = copy riêng trang chủ; UI_COPY = chrome dùng chung toàn site.
// Fallback chain: lang → en → vi. Nhãn điều hướng entity/hub KHÔNG nằm ở đây —
// dùng ROUTE_MAP.labels (routes.ts) làm nguồn duy nhất cho tên entity theo ngôn ngữ.

import type { Lang } from './types'
import { brand } from '../site.config'

const vi = {
  // Nhãn chung
  updated: 'Cập nhật',
  published: 'Ngày đăng',
  articleUpdated: 'Ngày sửa',
  overview: 'Tổng quan',
  details: 'Chi tiết',
  highlights: 'Điểm nổi bật',
  map: 'Bản đồ',
  address: 'Địa chỉ',
  phone: 'Điện thoại',
  website: 'Website',
  officialWebsite: 'Website chính thức',
  officialSource: 'Nguồn xác minh',
  category: 'Chuyên mục',
  faqHeading: 'Câu hỏi thường gặp',
  nearby: 'Gần đây',
  info: 'Thông tin',
  hours: 'Giờ mở cửa',
  type: 'Loại',
  date: 'Ngày',
  status: 'Trạng thái',
  start: 'Bắt đầu',
  end: 'Kết thúc',
  yes: 'Có',
  no: 'Không',
  notAvailable: 'Chưa có',
  view: 'Xem',
  roomsUnit: 'phòng',
  viewAll: 'Xem tất cả',
  results: 'kết quả',
  // Giá, vé, CTA
  free: 'Miễn phí',
  freeAdmission: 'Miễn phí',
  freeAccess: 'Tự do tham quan',
  paid: 'Có thu phí',
  admission: 'Phí vào cửa',
  price: 'Giá',
  priceFrom: 'Giá từ',
  ticketPrice: 'Giá vé',
  tickets: 'Vé',
  viewTickets: 'Xem vé',
  bookTicket: 'Đặt vé',
  bookNow: 'Đặt ngay',
  bookTour: 'Đặt tour',
  bookExperience: 'Đặt trải nghiệm',
  buyTickets: 'Mua vé',
  reservations: 'Đặt bàn',
  acceptsReservations: 'Nhận đặt bàn',
  checkAvailability: 'Xem phòng trống',
  // Kênh liên hệ (CONV-01)
  contactZalo: 'Chat Zalo',
  contactCall: 'Gọi điện',
  contactWhatsApp: 'WhatsApp',
  // Địa lý, tiếp cận
  howToGetThere: 'Cách tới nơi',
  distance: 'Khoảng cách',
  airport: 'Cách sân bay',
  beach: 'Ra biển',
  beachfront: 'Sát biển',
  notBeachfront: 'Không sát biển',
  departureSchedule: 'Lịch khởi hành',
  area: 'Diện tích',
  partOf: 'Thuộc',
  locationAt: 'Diễn ra tại',
  venue: 'Diễn ra tại',
  verifyWikidata: 'Xác minh trên Wikidata',
  // Lưu trú
  starRating: 'Hạng sao',
  stars: 'Hạng sao',
  rooms: 'Số phòng',
  checkin: 'Nhận phòng',
  checkout: 'Trả phòng',
  pets: 'Thú cưng',
  petsAllowed: 'Nhận thú cưng',
  allowed: 'Cho phép',
  amenities: 'Tiện ích',
  similarStays: 'Chỗ ở tương tự',
  onSiteActivities: 'Hoạt động tại chỗ',
  activities: 'Hoạt động',
  // Ẩm thực
  cuisine: 'Ẩm thực',
  menu: 'Menu',
  signatureDishes: 'Món đặc sắc',
  aboutRestaurant: 'Về nhà hàng',
  whereToEat: 'Ăn ở đâu',
  whereToTry: 'Ăn ở đâu',
  origin: 'Gốc gác',
  season: 'Mùa',
  bestSeason: 'Mùa thích hợp',
  // Tour, trải nghiệm
  duration: 'Thời lượng',
  format: 'Hình thức',
  departure: 'Khởi hành',
  tripOrigin: 'Xuất phát',
  operator: 'Đơn vị',
  suitableFor: 'Phù hợp',
  itinerary: 'Lịch trình',
  includesExcludes: 'Bao gồm / Không bao gồm',
  includes: 'Bao gồm',
  excludes: 'Không bao gồm',
  similarTours: 'Tour tương tự',
  similarExperiences: 'Trải nghiệm tương tự',
  experiencesHere: 'Trải nghiệm tại đây',
  toursAndEvents: 'Tour và sự kiện',
  // Sự kiện
  eventType: 'Loại sự kiện',
  organizer: 'Tổ chức bởi',
  past: 'Đã diễn ra',
  upcomingEvents: 'Sự kiện sắp diễn ra',
  pastEvents: 'Sự kiện đã diễn ra',
  noUpcomingEvents: 'Chưa có sự kiện sắp tới',
  otherEvents: 'Sự kiện khác',
  // Bài viết, người, tổ chức
  author: 'Tác giả',
  role: 'Vai trò',
  knowsAbout: 'Am hiểu',
  articlesBy: 'Bài đã viết',
  relatedArticles: 'Bài viết liên quan',
  aboutEntity: 'Nói về',
  mentions: 'Nhắc đến',
  howTo: 'Hướng dẫn',
  license: 'Giấy phép',
  office: 'Văn phòng',
  // Header / Footer / điều hướng
  skipNav: 'Bỏ qua điều hướng',
  homeAria: `${brand.name} — Trang chủ`,
  mainNavAria: 'Điều hướng chính',
  secondaryNavAria: 'Điều hướng phụ',
  chooseLangAria: 'Chọn ngôn ngữ',
  translationPending: 'Bản dịch đang được chuẩn bị',
  openMenu: 'Mở menu',
  closeMenu: 'Đóng menu',
  breadcrumbHome: 'Trang chủ',
  breadcrumbAria: 'Đường dẫn điều hướng',
  goHome: 'Xem trang chủ',
  galleryAria: 'Thư viện ảnh',
  readMore: 'Đọc tiếp',
  authorityAria: 'Thông tin thẩm quyền nội dung',
  footerTagline: 'Cẩm nang du lịch Nha Trang — thông tin điểm đến, trải nghiệm, ẩm thực và lưu trú được tuyển chọn bởi người bản địa.',
  footerServices: 'Dịch vụ',
  footerAboutUs: 'Về chúng tôi',
  footerGuides: 'Cẩm nang du lịch',
  footerIntro: 'Giới thiệu',
  footerContact: 'Liên hệ',
  footerDisclaimer: 'Thông tin chỉ mang tính tham khảo. Vui lòng kiểm tra giá và tình trạng trước khi đặt dịch vụ.',
  // Trang không tìm thấy
  notFoundTitle: `Không tìm thấy trang — ${brand.name}`,
  notFoundHeading: 'Không tìm thấy trang',
  notFoundBody: 'Nội dung bạn tìm chưa tồn tại hoặc chưa được phát hành.',
  emptyDefault: 'Chưa có nội dung nào',
}

export type UIKey = keyof typeof vi

const en: Record<UIKey, string> = {
  updated: 'Updated',
  published: 'Published',
  articleUpdated: 'Updated',
  overview: 'Overview',
  details: 'Details',
  highlights: 'Highlights',
  map: 'Map',
  address: 'Address',
  phone: 'Phone',
  website: 'Website',
  officialWebsite: 'Official website',
  officialSource: 'Official source',
  category: 'Category',
  faqHeading: 'Frequently asked questions',
  nearby: 'Nearby',
  info: 'Info',
  hours: 'Hours',
  type: 'Type',
  date: 'Date',
  status: 'Status',
  start: 'Start',
  end: 'End',
  yes: 'Yes',
  no: 'No',
  notAvailable: 'N/A',
  view: 'View',
  roomsUnit: 'rooms',
  viewAll: 'View all',
  results: 'results',
  free: 'Free',
  freeAdmission: 'Free admission',
  freeAccess: 'Free access',
  paid: 'Paid',
  admission: 'Admission',
  price: 'Price',
  priceFrom: 'From',
  ticketPrice: 'Tickets',
  tickets: 'Tickets',
  viewTickets: 'View tickets',
  bookTicket: 'Book tickets',
  bookNow: 'Book now',
  bookTour: 'Book tour',
  bookExperience: 'Book experience',
  buyTickets: 'Get tickets',
  reservations: 'Reservations',
  acceptsReservations: 'Accepts reservations',
  checkAvailability: 'Check availability',
  contactZalo: 'Chat on Zalo',
  contactCall: 'Call now',
  contactWhatsApp: 'WhatsApp',
  howToGetThere: 'How to get there',
  distance: 'Distance',
  airport: 'Airport',
  beach: 'Beach',
  beachfront: 'Beachfront',
  notBeachfront: 'Not beachfront',
  departureSchedule: 'Departure schedule',
  area: 'Area',
  partOf: 'Part of',
  locationAt: 'Location',
  venue: 'Venue',
  verifyWikidata: 'Verify on Wikidata',
  starRating: 'Star rating',
  stars: 'Stars',
  rooms: 'Rooms',
  checkin: 'Check-in',
  checkout: 'Check-out',
  pets: 'Pets',
  petsAllowed: 'Pets allowed',
  allowed: 'Allowed',
  amenities: 'Amenities',
  similarStays: 'Similar stays',
  onSiteActivities: 'On-site activities',
  activities: 'Activities',
  cuisine: 'Cuisine',
  menu: 'Menu',
  signatureDishes: 'Specialties',
  aboutRestaurant: 'About',
  whereToEat: 'Where to eat',
  whereToTry: 'Where to try',
  origin: 'Origin',
  season: 'Season',
  bestSeason: 'Best season',
  duration: 'Duration',
  format: 'Format',
  departure: 'Departure',
  tripOrigin: 'Origin',
  operator: 'Operator',
  suitableFor: 'For',
  itinerary: 'Itinerary',
  includesExcludes: 'Includes / Excludes',
  includes: 'Includes',
  excludes: 'Excludes',
  similarTours: 'Similar tours',
  similarExperiences: 'Similar experiences',
  experiencesHere: 'Experiences here',
  toursAndEvents: 'Tours & events',
  eventType: 'Event type',
  organizer: 'Organizer',
  past: 'Past',
  upcomingEvents: 'Upcoming events',
  pastEvents: 'Past events',
  noUpcomingEvents: 'No upcoming events',
  otherEvents: 'Other events',
  author: 'Author',
  role: 'Role',
  knowsAbout: 'Knows about',
  articlesBy: 'Articles',
  relatedArticles: 'Related articles',
  aboutEntity: 'About',
  mentions: 'Also mentions',
  howTo: 'How to',
  license: 'License',
  office: 'Office',
  skipNav: 'Skip navigation',
  homeAria: `${brand.name} — Home`,
  mainNavAria: 'Main navigation',
  secondaryNavAria: 'Secondary navigation',
  chooseLangAria: 'Choose language',
  translationPending: 'Translation in progress',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  breadcrumbHome: 'Home',
  breadcrumbAria: 'Breadcrumb',
  goHome: 'Go to homepage',
  galleryAria: 'Photo gallery',
  readMore: 'Read more',
  authorityAria: 'Content authority information',
  footerTagline: 'Nha Trang travel guide — destinations, experiences, food and stays curated by locals.',
  footerServices: 'Services',
  footerAboutUs: 'About us',
  footerGuides: 'Travel guides',
  footerIntro: 'About',
  footerContact: 'Contact',
  footerDisclaimer: 'Information is for reference only. Please check prices and availability before booking.',
  notFoundTitle: `Page not found — ${brand.name}`,
  notFoundHeading: 'Page not found',
  notFoundBody: 'The content you are looking for does not exist or has not been published.',
  emptyDefault: 'No content yet',
}

const zh: Record<UIKey, string> = {
  updated: '更新',
  published: '发布日期',
  articleUpdated: '更新日期',
  overview: '概览',
  details: '详情',
  highlights: '亮点',
  map: '地图',
  address: '地址',
  phone: '电话',
  website: '网站',
  officialWebsite: '官方网站',
  officialSource: '官方来源',
  category: '类别',
  faqHeading: '常见问题',
  nearby: '附近',
  info: '信息',
  hours: '开放时间',
  type: '类型',
  date: '日期',
  status: '状态',
  start: '开始',
  end: '结束',
  yes: '是',
  no: '否',
  notAvailable: '暂无',
  view: '查看',
  roomsUnit: '间客房',
  viewAll: '查看全部',
  results: '条结果',
  free: '免费',
  freeAdmission: '免费入场',
  freeAccess: '自由参观',
  paid: '收费',
  admission: '门票',
  price: '价格',
  priceFrom: '价格自',
  ticketPrice: '票价',
  tickets: '门票',
  viewTickets: '查看门票',
  bookTicket: '预订门票',
  bookNow: '立即预订',
  bookTour: '预订行程',
  bookExperience: '预订体验',
  buyTickets: '购票',
  reservations: '订座',
  acceptsReservations: '接受订座',
  checkAvailability: '查看空房',
  contactZalo: 'Zalo 咨询',
  contactCall: '致电',
  contactWhatsApp: 'WhatsApp',
  howToGetThere: '交通指南',
  distance: '距离',
  airport: '距机场',
  beach: '到海滩',
  beachfront: '一线海滨',
  notBeachfront: '非一线海滨',
  departureSchedule: '出发安排',
  area: '面积',
  partOf: '所属',
  locationAt: '地点',
  venue: '场地',
  verifyWikidata: '在 Wikidata 核实',
  starRating: '星级',
  stars: '星级',
  rooms: '房间数',
  checkin: '入住',
  checkout: '退房',
  pets: '宠物',
  petsAllowed: '可携宠物',
  allowed: '允许',
  amenities: '设施',
  similarStays: '类似住宿',
  onSiteActivities: '园内活动',
  activities: '活动',
  cuisine: '菜系',
  menu: '菜单',
  signatureDishes: '招牌菜',
  aboutRestaurant: '关于餐厅',
  whereToEat: '去哪吃',
  whereToTry: '去哪尝',
  origin: '来历',
  season: '季节',
  bestSeason: '最佳季节',
  duration: '时长',
  format: '形式',
  departure: '出发',
  tripOrigin: '出发地',
  operator: '运营方',
  suitableFor: '适合',
  itinerary: '行程',
  includesExcludes: '包含 / 不包含',
  includes: '包含',
  excludes: '不包含',
  similarTours: '类似行程',
  similarExperiences: '类似体验',
  experiencesHere: '这里的体验',
  toursAndEvents: '行程与活动',
  eventType: '活动类型',
  organizer: '主办方',
  past: '已结束',
  upcomingEvents: '即将举行的活动',
  pastEvents: '已结束的活动',
  noUpcomingEvents: '暂无即将举行的活动',
  otherEvents: '其他活动',
  author: '作者',
  role: '职务',
  knowsAbout: '擅长领域',
  articlesBy: '撰写文章',
  relatedArticles: '相关文章',
  aboutEntity: '介绍对象',
  mentions: '另提及',
  howTo: '操作指南',
  license: '执照',
  office: '办公室',
  skipNav: '跳过导航',
  homeAria: `${brand.name} — 首页`,
  mainNavAria: '主导航',
  secondaryNavAria: '次导航',
  chooseLangAria: '选择语言',
  translationPending: '译文准备中',
  openMenu: '打开菜单',
  closeMenu: '关闭菜单',
  breadcrumbHome: '首页',
  breadcrumbAria: '面包屑导航',
  goHome: '返回首页',
  galleryAria: '图库',
  readMore: '阅读更多',
  authorityAria: '内容权威信息',
  footerTagline: '芽庄旅行指南 — 由本地人精选的目的地、体验、美食与住宿信息。',
  footerServices: '服务',
  footerAboutUs: '关于我们',
  footerGuides: '旅行攻略',
  footerIntro: '简介',
  footerContact: '联系我们',
  footerDisclaimer: '信息仅供参考。预订前请核实价格与情况。',
  notFoundTitle: `页面未找到 — ${brand.name}`,
  notFoundHeading: '页面未找到',
  notFoundBody: '您查找的内容不存在或尚未发布。',
  emptyDefault: '暂无内容',
}

const ko: Record<UIKey, string> = {
  updated: '업데이트',
  published: '게시일',
  articleUpdated: '수정일',
  overview: '개요',
  details: '상세 정보',
  highlights: '하이라이트',
  map: '지도',
  address: '주소',
  phone: '전화',
  website: '웹사이트',
  officialWebsite: '공식 웹사이트',
  officialSource: '공식 출처',
  category: '카테고리',
  faqHeading: '자주 묻는 질문',
  nearby: '주변',
  info: '정보',
  hours: '운영 시간',
  type: '유형',
  date: '날짜',
  status: '상태',
  start: '시작',
  end: '종료',
  yes: '예',
  no: '아니요',
  notAvailable: '정보 없음',
  view: '보기',
  roomsUnit: '개 객실',
  viewAll: '전체 보기',
  results: '개 결과',
  free: '무료',
  freeAdmission: '무료 입장',
  freeAccess: '자유 관람',
  paid: '유료',
  admission: '입장료',
  price: '가격',
  priceFrom: '최저가',
  ticketPrice: '티켓 가격',
  tickets: '티켓',
  viewTickets: '티켓 보기',
  bookTicket: '티켓 예약',
  bookNow: '지금 예약',
  bookTour: '투어 예약',
  bookExperience: '체험 예약',
  buyTickets: '티켓 구매',
  reservations: '예약',
  acceptsReservations: '예약 가능',
  checkAvailability: '객실 확인',
  contactZalo: 'Zalo 상담',
  contactCall: '전화 문의',
  contactWhatsApp: 'WhatsApp',
  howToGetThere: '가는 방법',
  distance: '거리',
  airport: '공항까지',
  beach: '해변까지',
  beachfront: '비치프런트',
  notBeachfront: '비치프런트 아님',
  departureSchedule: '출발 일정',
  area: '면적',
  partOf: '소속',
  locationAt: '장소',
  venue: '장소',
  verifyWikidata: 'Wikidata에서 확인',
  starRating: '성급',
  stars: '성급',
  rooms: '객실 수',
  checkin: '체크인',
  checkout: '체크아웃',
  pets: '반려동물',
  petsAllowed: '반려동물 동반 가능',
  allowed: '허용',
  amenities: '편의시설',
  similarStays: '비슷한 숙소',
  onSiteActivities: '시설 내 액티비티',
  activities: '액티비티',
  cuisine: '요리',
  menu: '메뉴',
  signatureDishes: '대표 메뉴',
  aboutRestaurant: '레스토랑 소개',
  whereToEat: '어디서 먹을까',
  whereToTry: '어디서 맛볼까',
  origin: '유래',
  season: '시즌',
  bestSeason: '추천 시즌',
  duration: '소요 시간',
  format: '형태',
  departure: '출발',
  tripOrigin: '출발지',
  operator: '운영사',
  suitableFor: '적합 대상',
  itinerary: '일정',
  includesExcludes: '포함 / 불포함',
  includes: '포함',
  excludes: '불포함',
  similarTours: '비슷한 투어',
  similarExperiences: '비슷한 체험',
  experiencesHere: '이곳의 체험',
  toursAndEvents: '투어 & 이벤트',
  eventType: '이벤트 유형',
  organizer: '주최',
  past: '종료됨',
  upcomingEvents: '다가오는 이벤트',
  pastEvents: '지난 이벤트',
  noUpcomingEvents: '예정된 이벤트가 없습니다',
  otherEvents: '다른 이벤트',
  author: '작성자',
  role: '역할',
  knowsAbout: '전문 분야',
  articlesBy: '작성한 글',
  relatedArticles: '관련 글',
  aboutEntity: '다루는 주제',
  mentions: '함께 언급',
  howTo: '방법',
  license: '라이선스',
  office: '사무실',
  skipNav: '내비게이션 건너뛰기',
  homeAria: `${brand.name} — 홈`,
  mainNavAria: '주 메뉴',
  secondaryNavAria: '보조 메뉴',
  chooseLangAria: '언어 선택',
  translationPending: '번역 준비 중',
  openMenu: '메뉴 열기',
  closeMenu: '메뉴 닫기',
  breadcrumbHome: '홈',
  breadcrumbAria: '탐색 경로',
  goHome: '홈으로 가기',
  galleryAria: '사진 갤러리',
  readMore: '더 보기',
  authorityAria: '콘텐츠 신뢰성 정보',
  footerTagline: '나트랑 여행 가이드 — 현지인이 엄선한 명소, 체험, 음식, 숙소 정보.',
  footerServices: '서비스',
  footerAboutUs: '소개',
  footerGuides: '여행 가이드',
  footerIntro: '사이트 소개',
  footerContact: '문의',
  footerDisclaimer: '정보는 참고용입니다. 예약 전 가격과 상태를 확인하세요.',
  notFoundTitle: `페이지를 찾을 수 없음 — ${brand.name}`,
  notFoundHeading: '페이지를 찾을 수 없습니다',
  notFoundBody: '찾으시는 콘텐츠가 없거나 아직 게시되지 않았습니다.',
  emptyDefault: '아직 콘텐츠가 없습니다',
}

const ru: Record<UIKey, string> = {
  updated: 'Обновлено',
  published: 'Дата публикации',
  articleUpdated: 'Дата обновления',
  overview: 'Обзор',
  details: 'Подробности',
  highlights: 'Особенности',
  map: 'Карта',
  address: 'Адрес',
  phone: 'Телефон',
  website: 'Сайт',
  officialWebsite: 'Официальный сайт',
  officialSource: 'Официальный источник',
  category: 'Категория',
  faqHeading: 'Частые вопросы',
  nearby: 'Рядом',
  info: 'Информация',
  hours: 'Часы работы',
  type: 'Тип',
  date: 'Дата',
  status: 'Статус',
  start: 'Начало',
  end: 'Окончание',
  yes: 'Да',
  no: 'Нет',
  notAvailable: 'Нет данных',
  view: 'Открыть',
  roomsUnit: 'номеров',
  viewAll: 'Смотреть все',
  results: 'результатов',
  free: 'Бесплатно',
  freeAdmission: 'Вход свободный',
  freeAccess: 'Свободный доступ',
  paid: 'Платно',
  admission: 'Входная плата',
  price: 'Цена',
  priceFrom: 'Цена от',
  ticketPrice: 'Цена билета',
  tickets: 'Билеты',
  viewTickets: 'Посмотреть билеты',
  bookTicket: 'Купить билеты',
  bookNow: 'Забронировать',
  bookTour: 'Забронировать тур',
  bookExperience: 'Забронировать',
  buyTickets: 'Купить билеты',
  reservations: 'Бронь столика',
  acceptsReservations: 'Принимает брони',
  checkAvailability: 'Проверить наличие',
  contactZalo: 'Чат в Zalo',
  contactCall: 'Позвонить',
  contactWhatsApp: 'WhatsApp',
  howToGetThere: 'Как добраться',
  distance: 'Расстояние',
  airport: 'До аэропорта',
  beach: 'До пляжа',
  beachfront: 'Первая линия',
  notBeachfront: 'Не первая линия',
  departureSchedule: 'Расписание выезда',
  area: 'Площадь',
  partOf: 'Часть',
  locationAt: 'Место проведения',
  venue: 'Площадка',
  verifyWikidata: 'Проверить в Wikidata',
  starRating: 'Звёздность',
  stars: 'Звёзды',
  rooms: 'Номера',
  checkin: 'Заезд',
  checkout: 'Выезд',
  pets: 'Питомцы',
  petsAllowed: 'Можно с питомцами',
  allowed: 'Разрешено',
  amenities: 'Удобства',
  similarStays: 'Похожие варианты',
  onSiteActivities: 'Активности на территории',
  activities: 'Активности',
  cuisine: 'Кухня',
  menu: 'Меню',
  signatureDishes: 'Фирменные блюда',
  aboutRestaurant: 'О ресторане',
  whereToEat: 'Где поесть',
  whereToTry: 'Где попробовать',
  origin: 'Происхождение',
  season: 'Сезон',
  bestSeason: 'Лучший сезон',
  duration: 'Длительность',
  format: 'Формат',
  departure: 'Отправление',
  tripOrigin: 'Пункт отправления',
  operator: 'Оператор',
  suitableFor: 'Подходит для',
  itinerary: 'Маршрут',
  includesExcludes: 'Включено / Не включено',
  includes: 'Включено',
  excludes: 'Не включено',
  similarTours: 'Похожие туры',
  similarExperiences: 'Похожие впечатления',
  experiencesHere: 'Чем заняться здесь',
  toursAndEvents: 'Туры и события',
  eventType: 'Тип события',
  organizer: 'Организатор',
  past: 'Завершено',
  upcomingEvents: 'Предстоящие события',
  pastEvents: 'Прошедшие события',
  noUpcomingEvents: 'Нет предстоящих событий',
  otherEvents: 'Другие события',
  author: 'Автор',
  role: 'Роль',
  knowsAbout: 'Специализация',
  articlesBy: 'Статьи',
  relatedArticles: 'Похожие статьи',
  aboutEntity: 'О чём статья',
  mentions: 'Также упоминается',
  howTo: 'Инструкция',
  license: 'Лицензия',
  office: 'Офис',
  skipNav: 'Пропустить навигацию',
  homeAria: `${brand.name} — Главная`,
  mainNavAria: 'Основная навигация',
  secondaryNavAria: 'Дополнительная навигация',
  chooseLangAria: 'Выбор языка',
  translationPending: 'Перевод готовится',
  openMenu: 'Открыть меню',
  closeMenu: 'Закрыть меню',
  breadcrumbHome: 'Главная',
  breadcrumbAria: 'Навигационная цепочка',
  goHome: 'На главную',
  galleryAria: 'Фотогалерея',
  readMore: 'Читать далее',
  authorityAria: 'Информация о достоверности контента',
  footerTagline: 'Путеводитель по Нячангу — места, впечатления, еда и жильё, отобранные местными жителями.',
  footerServices: 'Сервисы',
  footerAboutUs: 'О нас',
  footerGuides: 'Путеводители',
  footerIntro: 'О сайте',
  footerContact: 'Контакты',
  footerDisclaimer: 'Информация носит справочный характер. Проверяйте цены и условия перед бронированием.',
  notFoundTitle: `Страница не найдена — ${brand.name}`,
  notFoundHeading: 'Страница не найдена',
  notFoundBody: 'Искомый контент не существует или ещё не опубликован.',
  emptyDefault: 'Пока нет контента',
}

export const UI_COPY: Record<Lang, Record<UIKey, string>> = { vi, en, zh, ko, ru }

/** Helper lookup theo lang, fallback chain lang → en → vi. */
export function uiCopy(lang: Lang): (key: UIKey) => string {
  return (key) => UI_COPY[lang]?.[key] ?? UI_COPY.en[key] ?? UI_COPY.vi[key]
}

// ---------- Dictionary enum → nhãn hiển thị (đủ 5 ngôn ngữ) ----------

export type LabelDict = Record<Lang, Record<string, string>>

/** Lookup dictionary với fallback chain lang → en → vi → chính code. */
export function typeLabel(dict: LabelDict, lang: Lang, code: string | undefined): string {
  if (!code) return ''
  return dict[lang]?.[code] ?? dict.en?.[code] ?? dict.vi?.[code] ?? code
}

export const ATTRACTION_TYPE_LABELS: LabelDict = {
  vi: { historic: 'Di tích', temple: 'Chùa', church: 'Nhà thờ', museum: 'Bảo tàng', 'theme-park': 'Công viên giải trí', aquarium: 'Thủy cung', 'mud-spa': 'Tắm bùn', market: 'Chợ', park: 'Công viên' },
  en: { historic: 'Historic site', temple: 'Temple', church: 'Church', museum: 'Museum', 'theme-park': 'Theme park', aquarium: 'Aquarium', 'mud-spa': 'Mud spa', market: 'Market', park: 'Park' },
  zh: { historic: '古迹', temple: '寺庙', church: '教堂', museum: '博物馆', 'theme-park': '主题公园', aquarium: '水族馆', 'mud-spa': '泥浆浴', market: '市场', park: '公园' },
  ko: { historic: '유적지', temple: '사원', church: '교회', museum: '박물관', 'theme-park': '테마파크', aquarium: '아쿠아리움', 'mud-spa': '머드 스파', market: '시장', park: '공원' },
  ru: { historic: 'Памятник истории', temple: 'Храм', church: 'Церковь', museum: 'Музей', 'theme-park': 'Парк развлечений', aquarium: 'Океанариум', 'mud-spa': 'Грязевой спа', market: 'Рынок', park: 'Парк' },
}

export const PLACE_TYPE_LABELS: LabelDict = {
  vi: { beach: 'Bãi biển', island: 'Đảo', landform: 'Địa hình', ward: 'Phường', area: 'Khu vực' },
  en: { beach: 'Beach', island: 'Island', landform: 'Landform', ward: 'Ward', area: 'Area' },
  zh: { beach: '海滩', island: '岛屿', landform: '地貌', ward: '坊', area: '区域' },
  ko: { beach: '해변', island: '섬', landform: '지형', ward: '동', area: '지역' },
  ru: { beach: 'Пляж', island: 'Остров', landform: 'Ландшафт', ward: 'Район', area: 'Зона' },
}

export const SPECIALTY_TYPE_LABELS: LabelDict = {
  vi: { dish: 'Món ăn', product: 'Sản vật' },
  en: { dish: 'Dish', product: 'Product' },
  zh: { dish: '菜品', product: '特产' },
  ko: { dish: '요리', product: '특산품' },
  ru: { dish: 'Блюдо', product: 'Продукт' },
}

export const ARTICLE_TYPE_LABELS: LabelDict = {
  vi: { guide: 'Cẩm nang', list: 'Danh sách', news: 'Tin tức', review: 'Đánh giá', itinerary: 'Hành trình', 'transport-guide': 'Đi lại' },
  en: { guide: 'Guide', list: 'List', news: 'News', review: 'Review', itinerary: 'Itinerary', 'transport-guide': 'Transport guide' },
  zh: { guide: '攻略', list: '清单', news: '新闻', review: '评价', itinerary: '行程', 'transport-guide': '交通指南' },
  ko: { guide: '가이드', list: '리스트', news: '뉴스', review: '리뷰', itinerary: '일정', 'transport-guide': '교통 가이드' },
  ru: { guide: 'Гайд', list: 'Список', news: 'Новости', review: 'Обзор', itinerary: 'Маршрут', 'transport-guide': 'Транспортный гайд' },
}

export const EVENT_TYPE_LABELS: LabelDict = {
  vi: { festival: 'Lễ hội', sports: 'Thể thao', music: 'Âm nhạc', food: 'Ẩm thực', exhibition: 'Triển lãm', other: 'Sự kiện' },
  en: { festival: 'Festival', sports: 'Sports', music: 'Music', food: 'Food', exhibition: 'Exhibition', other: 'Event' },
  zh: { festival: '节庆', sports: '体育', music: '音乐', food: '美食', exhibition: '展览', other: '活动' },
  ko: { festival: '축제', sports: '스포츠', music: '음악', food: '음식', exhibition: '전시', other: '이벤트' },
  ru: { festival: 'Фестиваль', sports: 'Спорт', music: 'Музыка', food: 'Еда', exhibition: 'Выставка', other: 'Событие' },
}

export const EVENT_STATUS_LABELS: LabelDict = {
  vi: { EventScheduled: 'Đã lên lịch', EventPostponed: 'Đã hoãn', EventRescheduled: 'Đã dời lịch', EventCancelled: 'Đã hủy' },
  en: { EventScheduled: 'Scheduled', EventPostponed: 'Postponed', EventRescheduled: 'Rescheduled', EventCancelled: 'Cancelled' },
  zh: { EventScheduled: '已排期', EventPostponed: '已推迟', EventRescheduled: '已改期', EventCancelled: '已取消' },
  ko: { EventScheduled: '예정', EventPostponed: '연기됨', EventRescheduled: '일정 변경', EventCancelled: '취소됨' },
  ru: { EventScheduled: 'Запланировано', EventPostponed: 'Отложено', EventRescheduled: 'Перенесено', EventCancelled: 'Отменено' },
}

export const ORG_TYPE_LABELS: LabelDict = {
  vi: { travelAgency: 'Đại lý du lịch', transportCompany: 'Công ty vận tải', diveOperator: 'Trung tâm lặn', dmc: 'DMC', organization: 'Tổ chức' },
  en: { travelAgency: 'Travel Agency', transportCompany: 'Transport Company', diveOperator: 'Dive Operator', dmc: 'DMC', organization: 'Organization' },
  zh: { travelAgency: '旅行社', transportCompany: '运输公司', diveOperator: '潜水中心', dmc: 'DMC', organization: '机构' },
  ko: { travelAgency: '여행사', transportCompany: '운송 회사', diveOperator: '다이빙 센터', dmc: 'DMC', organization: '기관' },
  ru: { travelAgency: 'Турагентство', transportCompany: 'Транспортная компания', diveOperator: 'Дайв-центр', dmc: 'DMC', organization: 'Организация' },
}

/** Nhãn tourFormat cho trang detail (Ghép đoàn / Tour riêng / Cả hai). */
export const TOUR_FORMAT_LABELS: LabelDict = {
  vi: { 'join-in': 'Ghép đoàn', private: 'Tour riêng', both: 'Cả hai' },
  en: { 'join-in': 'Join-in', private: 'Private', both: 'Both' },
  zh: { 'join-in': '拼团', private: '包团', both: '两者皆可' },
  ko: { 'join-in': '조인 투어', private: '단독 투어', both: '모두 가능' },
  ru: { 'join-in': 'Групповой', private: 'Индивидуальный', both: 'Оба варианта' },
}

/** Badge tourFormat cho card/index (Tour ghép / Tour riêng / Linh hoạt). */
export const TOUR_FORMAT_BADGES: LabelDict = {
  vi: { 'join-in': 'Tour ghép', private: 'Tour riêng', both: 'Linh hoạt' },
  en: { 'join-in': 'Join-in', private: 'Private', both: 'Flexible' },
  zh: { 'join-in': '拼团', private: '包团', both: '灵活' },
  ko: { 'join-in': '조인 투어', private: '단독 투어', both: '유연' },
  ru: { 'join-in': 'Групповой', private: 'Индивидуальный', both: 'Гибкий' },
}

/** Nhãn CTA theo entityType (PriceDisplay). */
export const PRICE_CTA_LABELS: LabelDict = {
  vi: { hotel: 'Xem phòng trống', resort: 'Xem phòng trống', tour: 'Đặt tour', experience: 'Đặt trải nghiệm', attraction: 'Mua vé', event: 'Đặt vé', default: 'Đặt ngay' },
  en: { hotel: 'Check Availability', resort: 'Check Availability', tour: 'Book Tour', experience: 'Book Experience', attraction: 'Get Tickets', event: 'Get Tickets', default: 'Book Now' },
  zh: { hotel: '查看空房', resort: '查看空房', tour: '预订行程', experience: '预订体验', attraction: '购票', event: '购票', default: '立即预订' },
  ko: { hotel: '객실 확인', resort: '객실 확인', tour: '투어 예약', experience: '체험 예약', attraction: '티켓 구매', event: '티켓 구매', default: '지금 예약' },
  ru: { hotel: 'Проверить наличие', resort: 'Проверить наличие', tour: 'Забронировать тур', experience: 'Забронировать', attraction: 'Купить билеты', event: 'Купить билеты', default: 'Забронировать' },
}

/**
 * Template nhãn giá theo unit — dùng bởi resolvePrice (src/lib/resolver.ts).
 * price/asOf nhận chuỗi ĐÃ format theo locale (formatPrice, formatMonthYear).
 */
export interface PriceLabelTemplates {
  perPax: (price: string) => string
  perPaxFrom: (price: string) => string
  perNightFrom: (price: string, asOf: string) => string
  perTicketFrom: (price: string) => string
}

export const PRICE_LABEL_TEMPLATES: Record<Lang, PriceLabelTemplates> = {
  vi: {
    perPax: (p) => `${p}/người`,
    perPaxFrom: (p) => `từ ${p}/người`,
    perNightFrom: (p, asOf) => asOf ? `từ ${p}/đêm · cập nhật ${asOf}` : `từ ${p}/đêm`,
    perTicketFrom: (p) => `từ ${p}/vé`,
  },
  en: {
    perPax: (p) => `${p}/person`,
    perPaxFrom: (p) => `from ${p}/person`,
    perNightFrom: (p, asOf) => asOf ? `from ${p}/night · updated ${asOf}` : `from ${p}/night`,
    perTicketFrom: (p) => `from ${p}/ticket`,
  },
  zh: {
    perPax: (p) => `每人${p}`,
    perPaxFrom: (p) => `每人${p}起`,
    perNightFrom: (p, asOf) => asOf ? `每晚${p}起 · 更新于${asOf}` : `每晚${p}起`,
    perTicketFrom: (p) => `每张${p}起`,
  },
  ko: {
    perPax: (p) => `1인 ${p}`,
    perPaxFrom: (p) => `1인 ${p}부터`,
    perNightFrom: (p, asOf) => asOf ? `1박 ${p}부터 · ${asOf} 업데이트` : `1박 ${p}부터`,
    perTicketFrom: (p) => `티켓 ${p}부터`,
  },
  ru: {
    perPax: (p) => `${p}/чел.`,
    perPaxFrom: (p) => `от ${p}/чел.`,
    perNightFrom: (p, asOf) => asOf ? `от ${p}/ночь · обновлено ${asOf}` : `от ${p}/ночь`,
    perTicketFrom: (p) => `от ${p}/билет`,
  },
}

/** Thông điệp EmptyState theo entityType. */
export const EMPTY_STATE_MESSAGES: LabelDict = {
  vi: { place: 'Chưa có địa danh nào', attraction: 'Chưa có điểm tham quan nào', experience: 'Chưa có trải nghiệm nào', restaurant: 'Chưa có nhà hàng nào', specialty: 'Chưa có đặc sản nào', hotel: 'Chưa có khách sạn nào', resort: 'Chưa có resort nào', tour: 'Chưa có tour nào', event: 'Chưa có sự kiện nào', article: 'Chưa có bài viết nào', hub: 'Chưa có nội dung nào' },
  en: { place: 'No places yet', attraction: 'No attractions yet', experience: 'No experiences yet', restaurant: 'No restaurants yet', specialty: 'No specialties yet', hotel: 'No hotels yet', resort: 'No resorts yet', tour: 'No tours yet', event: 'No events yet', article: 'No articles yet', hub: 'No content yet' },
  zh: { place: '暂无地点', attraction: '暂无景点', experience: '暂无体验', restaurant: '暂无餐厅', specialty: '暂无特产', hotel: '暂无酒店', resort: '暂无度假村', tour: '暂无行程', event: '暂无活动', article: '暂无文章', hub: '暂无内容' },
  ko: { place: '아직 장소가 없습니다', attraction: '아직 명소가 없습니다', experience: '아직 체험이 없습니다', restaurant: '아직 맛집이 없습니다', specialty: '아직 특산품이 없습니다', hotel: '아직 호텔이 없습니다', resort: '아직 리조트가 없습니다', tour: '아직 투어가 없습니다', event: '아직 이벤트가 없습니다', article: '아직 글이 없습니다', hub: '아직 콘텐츠가 없습니다' },
  ru: { place: 'Пока нет мест', attraction: 'Пока нет достопримечательностей', experience: 'Пока нет впечатлений', restaurant: 'Пока нет ресторанов', specialty: 'Пока нет деликатесов', hotel: 'Пока нет отелей', resort: 'Пока нет курортов', tour: 'Пока нет туров', event: 'Пока нет событий', article: 'Пока нет статей', hub: 'Пока нет контента' },
}

// ---------- Copy trang index / hub (RouteDispatch) ----------

export interface PageCopy { title: string; desc: string }

export const INDEX_COPY: Record<Lang, Record<string, PageCopy>> = {
  vi: {
    place:        { title: 'Địa danh', desc: 'Các địa danh tại Nha Trang và Khánh Hòa.' },
    attraction:   { title: 'Điểm tham quan', desc: 'Điểm tham quan nổi bật ở Nha Trang.' },
    experience:   { title: 'Trải nghiệm', desc: 'Hoạt động và trải nghiệm tại Nha Trang.' },
    restaurant:   { title: 'Nhà hàng', desc: 'Nhà hàng và quán ăn ở Nha Trang.' },
    specialty:    { title: 'Đặc sản', desc: 'Đặc sản và món ngon Khánh Hòa.' },
    hotel:        { title: 'Khách sạn', desc: 'Khách sạn tại Nha Trang.' },
    resort:       { title: 'Resort', desc: 'Resort nghỉ dưỡng ở Nha Trang.' },
    article:      { title: 'Cẩm nang', desc: 'Cẩm nang và hướng dẫn du lịch Nha Trang.' },
    tour:         { title: 'Tour', desc: 'Tour và hành trình tại Nha Trang.' },
    event:        { title: 'Sự kiện', desc: 'Sự kiện và lễ hội ở Nha Trang.' },
    person:       { title: 'Tác giả', desc: `Tác giả và chuyên gia nội dung của ${brand.name}.` },
    organization: { title: 'Công ty', desc: 'Đơn vị vận hành tour, sự kiện và dịch vụ liên quan.' },
  },
  en: {
    place:        { title: 'Places', desc: 'Places across Nha Trang and Khanh Hoa.' },
    attraction:   { title: 'Attractions', desc: 'Notable attractions in Nha Trang.' },
    experience:   { title: 'Experiences', desc: 'Activities and experiences in Nha Trang.' },
    restaurant:   { title: 'Restaurants', desc: 'Restaurants and eateries in Nha Trang.' },
    specialty:    { title: 'Specialties', desc: 'Local specialties and dishes of Khanh Hoa.' },
    hotel:        { title: 'Hotels', desc: 'Hotels in Nha Trang.' },
    resort:       { title: 'Resorts', desc: 'Beach resorts in Nha Trang.' },
    article:      { title: 'Guides', desc: 'Nha Trang travel guides and how-tos.' },
    tour:         { title: 'Tours', desc: 'Tours and itineraries in Nha Trang.' },
    event:        { title: 'Events', desc: 'Events and festivals in Nha Trang.' },
    person:       { title: 'Authors', desc: `Authors and content experts of ${brand.name}.` },
    organization: { title: 'Companies', desc: 'Operators of tours, events and related services.' },
  },
  zh: {
    place:        { title: '地点', desc: '芽庄与庆和的各处地点。' },
    attraction:   { title: '景点', desc: '芽庄的著名景点。' },
    experience:   { title: '体验', desc: '芽庄的活动与体验。' },
    restaurant:   { title: '餐厅', desc: '芽庄的餐厅与小吃店。' },
    specialty:    { title: '特产', desc: '庆和的特产与美食。' },
    hotel:        { title: '酒店', desc: '芽庄的酒店。' },
    resort:       { title: '度假村', desc: '芽庄的海滨度假村。' },
    article:      { title: '攻略', desc: '芽庄旅行攻略与指南。' },
    tour:         { title: '旅行团', desc: '芽庄的行程与线路。' },
    event:        { title: '活动', desc: '芽庄的活动与节庆。' },
    person:       { title: '作者', desc: `${brand.name} 的作者与内容专家。` },
    organization: { title: '公司', desc: '运营行程、活动及相关服务的机构。' },
  },
  ko: {
    place:        { title: '장소', desc: '나트랑과 카인호아의 장소들.' },
    attraction:   { title: '명소', desc: '나트랑의 주요 명소.' },
    experience:   { title: '체험', desc: '나트랑의 액티비티와 체험.' },
    restaurant:   { title: '맛집', desc: '나트랑의 레스토랑과 식당.' },
    specialty:    { title: '특산품', desc: '카인호아의 특산품과 맛있는 음식.' },
    hotel:        { title: '호텔', desc: '나트랑의 호텔.' },
    resort:       { title: '리조트', desc: '나트랑의 휴양 리조트.' },
    article:      { title: '가이드', desc: '나트랑 여행 가이드와 팁.' },
    tour:         { title: '투어', desc: '나트랑의 투어와 여정.' },
    event:        { title: '이벤트', desc: '나트랑의 이벤트와 축제.' },
    person:       { title: '작가', desc: `${brand.name}의 작가와 콘텐츠 전문가.` },
    organization: { title: '회사', desc: '투어, 이벤트 및 관련 서비스 운영사.' },
  },
  ru: {
    place:        { title: 'Места', desc: 'Места Нячанга и Кханьхоа.' },
    attraction:   { title: 'Достопримечательности', desc: 'Известные достопримечательности Нячанга.' },
    experience:   { title: 'Впечатления', desc: 'Активности и впечатления в Нячанге.' },
    restaurant:   { title: 'Рестораны', desc: 'Рестораны и закусочные Нячанга.' },
    specialty:    { title: 'Деликатесы', desc: 'Деликатесы и блюда Кханьхоа.' },
    hotel:        { title: 'Отели', desc: 'Отели Нячанга.' },
    resort:       { title: 'Курорты', desc: 'Пляжные курорты Нячанга.' },
    article:      { title: 'Гайды', desc: 'Путеводители и советы по Нячангу.' },
    tour:         { title: 'Туры', desc: 'Туры и маршруты в Нячанге.' },
    event:        { title: 'События', desc: 'События и фестивали Нячанга.' },
    person:       { title: 'Авторы', desc: `Авторы и эксперты ${brand.name}.` },
    organization: { title: 'Компании', desc: 'Операторы туров, событий и сопутствующих услуг.' },
  },
}

export const HUB_COPY: Record<Lang, Record<string, PageCopy>> = {
  vi: {
    'hub-kham-pha': { title: 'Khám phá Nha Trang', desc: 'Điểm tham quan và trải nghiệm nổi bật tại Nha Trang.' },
    'hub-luu-tru':  { title: 'Lưu trú', desc: 'Khách sạn và resort tại Nha Trang cho nhiều nhu cầu lưu trú.' },
    'hub-di-lai':   { title: 'Đi lại', desc: 'Hướng dẫn di chuyển và kinh nghiệm đi lại ở Nha Trang.' },
    'hub-all':      { title: 'Tất cả chuyên mục', desc: `Danh mục đầy đủ các lớp nội dung và entity công khai của ${brand.name}.` },
  },
  en: {
    'hub-kham-pha': { title: 'Explore Nha Trang', desc: 'Notable attractions and experiences in Nha Trang.' },
    'hub-luu-tru':  { title: 'Where to stay', desc: 'Hotels and resorts in Nha Trang for every need.' },
    'hub-di-lai':   { title: 'Getting around', desc: 'Transport guides and travel tips for Nha Trang.' },
    'hub-all':      { title: 'All sections', desc: `The full catalogue of public content layers and entities of ${brand.name}.` },
  },
  zh: {
    'hub-kham-pha': { title: '探索芽庄', desc: '芽庄的著名景点与体验。' },
    'hub-luu-tru':  { title: '住宿', desc: '满足不同需求的芽庄酒店与度假村。' },
    'hub-di-lai':   { title: '交通', desc: '芽庄的交通指南与出行经验。' },
    'hub-all':      { title: '全部栏目', desc: `${brand.name} 公开内容与条目的完整目录。` },
  },
  ko: {
    'hub-kham-pha': { title: '나트랑 즐길거리', desc: '나트랑의 주요 명소와 체험.' },
    'hub-luu-tru':  { title: '숙소', desc: '다양한 니즈에 맞는 나트랑 호텔과 리조트.' },
    'hub-di-lai':   { title: '교통', desc: '나트랑 이동 가이드와 팁.' },
    'hub-all':      { title: '전체 카테고리', desc: `${brand.name}의 공개 콘텐츠와 엔티티 전체 목록.` },
  },
  ru: {
    'hub-kham-pha': { title: 'Развлечения в Нячанге', desc: 'Известные достопримечательности и впечатления Нячанга.' },
    'hub-luu-tru':  { title: 'Проживание', desc: 'Отели и курорты Нячанга на любой запрос.' },
    'hub-di-lai':   { title: 'Транспорт', desc: 'Транспортные гайды и советы по Нячангу.' },
    'hub-all':      { title: 'Все разделы', desc: `Полный каталог открытого контента и сущностей ${brand.name}.` },
  },
}

/** Copy phần (section) trong trang hub, key `${hubId}|${entity}`. */
export const HUB_PART_COPY: Record<Lang, Record<string, PageCopy>> = {
  vi: {
    'hub-kham-pha|attraction': { title: 'Điểm tham quan', desc: 'Những điểm tham quan nổi bật ở Nha Trang.' },
    'hub-kham-pha|experience': { title: 'Trải nghiệm', desc: 'Hoạt động và trải nghiệm nên thử tại Nha Trang.' },
    'hub-luu-tru|hotel':       { title: 'Khách sạn', desc: 'Khách sạn tại Nha Trang theo khu vực và nhu cầu.' },
    'hub-luu-tru|resort':      { title: 'Resort', desc: 'Resort nghỉ dưỡng ở Nha Trang và vùng lân cận.' },
    'hub-di-lai|article':      { title: 'Cẩm nang đi lại', desc: 'Hướng dẫn phương tiện, tuyến đường và mẹo di chuyển.' },
    'hub-all|place':           { title: 'Địa danh', desc: 'Khu vực, đảo, bãi biển và địa danh nền tảng.' },
    'hub-all|attraction':      { title: 'Điểm tham quan', desc: 'Điểm tham quan, di tích, công viên và điểm đến cụ thể.' },
    'hub-all|experience':      { title: 'Trải nghiệm', desc: 'Hoạt động và trải nghiệm nên thử.' },
    'hub-all|restaurant':      { title: 'Nhà hàng', desc: 'Nhà hàng và quán ăn đáng thử.' },
    'hub-all|specialty':       { title: 'Đặc sản', desc: 'Đặc sản và món ngon Khánh Hòa.' },
    'hub-all|hotel':           { title: 'Khách sạn', desc: 'Khách sạn theo khu vực và nhu cầu.' },
    'hub-all|resort':          { title: 'Resort', desc: 'Resort nghỉ dưỡng ở Nha Trang và vùng lân cận.' },
    'hub-all|tour':            { title: 'Tour', desc: 'Tour và hành trình có thể đặt hoặc tham khảo.' },
    'hub-all|event':           { title: 'Sự kiện', desc: 'Sự kiện, lễ hội và hoạt động theo thời gian.' },
    'hub-all|article':         { title: 'Cẩm nang', desc: 'Bài viết hướng dẫn, danh sách và kinh nghiệm địa phương.' },
    'hub-all|organization':    { title: 'Công ty', desc: 'Đơn vị vận hành tour, sự kiện và dịch vụ liên quan.' },
    'hub-all|person':          { title: 'Tác giả', desc: 'Tác giả và chuyên gia nội dung.' },
  },
  en: {
    'hub-kham-pha|attraction': { title: 'Attractions', desc: 'Notable attractions in Nha Trang.' },
    'hub-kham-pha|experience': { title: 'Experiences', desc: 'Activities and experiences worth trying in Nha Trang.' },
    'hub-luu-tru|hotel':       { title: 'Hotels', desc: 'Hotels in Nha Trang by area and need.' },
    'hub-luu-tru|resort':      { title: 'Resorts', desc: 'Resorts in Nha Trang and nearby.' },
    'hub-di-lai|article':      { title: 'Transport guides', desc: 'Guides on transport, routes and travel tips.' },
    'hub-all|place':           { title: 'Places', desc: 'Areas, islands, beaches and foundational places.' },
    'hub-all|attraction':      { title: 'Attractions', desc: 'Attractions, monuments, parks and specific destinations.' },
    'hub-all|experience':      { title: 'Experiences', desc: 'Activities and experiences worth trying.' },
    'hub-all|restaurant':      { title: 'Restaurants', desc: 'Restaurants and eateries worth trying.' },
    'hub-all|specialty':       { title: 'Specialties', desc: 'Specialties and dishes of Khanh Hoa.' },
    'hub-all|hotel':           { title: 'Hotels', desc: 'Hotels by area and need.' },
    'hub-all|resort':          { title: 'Resorts', desc: 'Resorts in Nha Trang and nearby.' },
    'hub-all|tour':            { title: 'Tours', desc: 'Tours and itineraries to book or browse.' },
    'hub-all|event':           { title: 'Events', desc: 'Events, festivals and time-based activities.' },
    'hub-all|article':         { title: 'Guides', desc: 'How-tos, lists and local tips.' },
    'hub-all|organization':    { title: 'Companies', desc: 'Operators of tours, events and related services.' },
    'hub-all|person':          { title: 'Authors', desc: 'Authors and content experts.' },
  },
  zh: {
    'hub-kham-pha|attraction': { title: '景点', desc: '芽庄的著名景点。' },
    'hub-kham-pha|experience': { title: '体验', desc: '芽庄值得一试的活动与体验。' },
    'hub-luu-tru|hotel':       { title: '酒店', desc: '按区域与需求划分的芽庄酒店。' },
    'hub-luu-tru|resort':      { title: '度假村', desc: '芽庄及周边的度假村。' },
    'hub-di-lai|article':      { title: '交通攻略', desc: '交通工具、路线与出行技巧指南。' },
    'hub-all|place':           { title: '地点', desc: '区域、岛屿、海滩等基础地点。' },
    'hub-all|attraction':      { title: '景点', desc: '景点、古迹、公园与具体目的地。' },
    'hub-all|experience':      { title: '体验', desc: '值得一试的活动与体验。' },
    'hub-all|restaurant':      { title: '餐厅', desc: '值得一试的餐厅与小吃店。' },
    'hub-all|specialty':       { title: '特产', desc: '庆和的特产与美食。' },
    'hub-all|hotel':           { title: '酒店', desc: '按区域与需求划分的酒店。' },
    'hub-all|resort':          { title: '度假村', desc: '芽庄及周边的度假村。' },
    'hub-all|tour':            { title: '旅行团', desc: '可预订或参考的行程。' },
    'hub-all|event':           { title: '活动', desc: '按时间排列的活动与节庆。' },
    'hub-all|article':         { title: '攻略', desc: '指南、清单与本地经验。' },
    'hub-all|organization':    { title: '公司', desc: '运营行程、活动及相关服务的机构。' },
    'hub-all|person':          { title: '作者', desc: '作者与内容专家。' },
  },
  ko: {
    'hub-kham-pha|attraction': { title: '명소', desc: '나트랑의 주요 명소.' },
    'hub-kham-pha|experience': { title: '체험', desc: '나트랑에서 해볼 만한 액티비티와 체험.' },
    'hub-luu-tru|hotel':       { title: '호텔', desc: '지역과 니즈별 나트랑 호텔.' },
    'hub-luu-tru|resort':      { title: '리조트', desc: '나트랑과 인근의 리조트.' },
    'hub-di-lai|article':      { title: '교통 가이드', desc: '교통수단, 노선, 이동 팁 가이드.' },
    'hub-all|place':           { title: '장소', desc: '지역, 섬, 해변 등 기반 장소.' },
    'hub-all|attraction':      { title: '명소', desc: '명소, 유적, 공원 등 구체적 목적지.' },
    'hub-all|experience':      { title: '체험', desc: '해볼 만한 액티비티와 체험.' },
    'hub-all|restaurant':      { title: '맛집', desc: '가볼 만한 레스토랑과 식당.' },
    'hub-all|specialty':       { title: '특산품', desc: '카인호아의 특산품과 음식.' },
    'hub-all|hotel':           { title: '호텔', desc: '지역과 니즈별 호텔.' },
    'hub-all|resort':          { title: '리조트', desc: '나트랑과 인근의 리조트.' },
    'hub-all|tour':            { title: '투어', desc: '예약하거나 참고할 수 있는 투어.' },
    'hub-all|event':           { title: '이벤트', desc: '시기별 이벤트, 축제, 활동.' },
    'hub-all|article':         { title: '가이드', desc: '가이드, 리스트, 현지 경험담.' },
    'hub-all|organization':    { title: '회사', desc: '투어, 이벤트 및 관련 서비스 운영사.' },
    'hub-all|person':          { title: '작가', desc: '작가와 콘텐츠 전문가.' },
  },
  ru: {
    'hub-kham-pha|attraction': { title: 'Достопримечательности', desc: 'Известные достопримечательности Нячанга.' },
    'hub-kham-pha|experience': { title: 'Впечатления', desc: 'Активности и впечатления, которые стоит попробовать в Нячанге.' },
    'hub-luu-tru|hotel':       { title: 'Отели', desc: 'Отели Нячанга по районам и запросам.' },
    'hub-luu-tru|resort':      { title: 'Курорты', desc: 'Курорты Нячанга и окрестностей.' },
    'hub-di-lai|article':      { title: 'Транспортные гайды', desc: 'Гайды по транспорту, маршрутам и советам в пути.' },
    'hub-all|place':           { title: 'Места', desc: 'Районы, острова, пляжи и базовые места.' },
    'hub-all|attraction':      { title: 'Достопримечательности', desc: 'Достопримечательности, памятники, парки и конкретные места.' },
    'hub-all|experience':      { title: 'Впечатления', desc: 'Активности и впечатления, которые стоит попробовать.' },
    'hub-all|restaurant':      { title: 'Рестораны', desc: 'Рестораны и закусочные, которые стоит попробовать.' },
    'hub-all|specialty':       { title: 'Деликатесы', desc: 'Деликатесы и блюда Кханьхоа.' },
    'hub-all|hotel':           { title: 'Отели', desc: 'Отели по районам и запросам.' },
    'hub-all|resort':          { title: 'Курорты', desc: 'Курорты Нячанга и окрестностей.' },
    'hub-all|tour':            { title: 'Туры', desc: 'Туры и маршруты для брони или изучения.' },
    'hub-all|event':           { title: 'События', desc: 'События, фестивали и активности по времени.' },
    'hub-all|article':         { title: 'Гайды', desc: 'Гайды, списки и местный опыт.' },
    'hub-all|organization':    { title: 'Компании', desc: 'Операторы туров, событий и сопутствующих услуг.' },
    'hub-all|person':          { title: 'Авторы', desc: 'Авторы и эксперты по контенту.' },
  },
}

/** Description fallback cho meta description trang detail/term. */
export function fallbackDescription(title: string, lang: Lang): string {
  const templates: Record<Lang, (t: string) => string> = {
    vi: (t) => `Thông tin du lịch ${t} tại Nha Trang và Khánh Hòa.`,
    en: (t) => `Travel information for ${t} in Nha Trang and Khanh Hoa.`,
    zh: (t) => `${t}的芽庄与庆和旅行信息。`,
    ko: (t) => `나트랑·카인호아의 ${t} 여행 정보.`,
    ru: (t) => `Туристическая информация о ${t} в Нячанге и Кханьхоа.`,
  }
  return (templates[lang] ?? templates.en)(title)
}
